### ISSUE TITLE
more sources

### ISSUE THREAD

**Issue by mspykerez** [jliddev/WowUp#10]
- Add wowinterface.com, GitLab, etc.
- Add wago.io to update auras and Plater profiles/scripts like WeakAuras Companion (similar to what this does: https://github.com/AcidWeb/CurseBreaker).
- Add update TradeSkillMaster data (similiar to what this does: https://github.com/camas/grunt).

**Comment by jliddev** [comment]
These sould probably be separate requests. wowinterface's api was a little rough to work with in the beginning so it would have to be revisted maybe from the install from URL button. Gitlab is the same thing, if there's an example addon that uses it?

I am not familiar with wago.io should probably be a separate request.

TSM is also a separate request please, im not sure what that is.

**Comment by mspykerez** [comment]
Should I open an issue for each of the 3 separated suggested sources?

- You mean you don't know wago.io  or you are not familiar on how to implement such a feature? its the most used website where you post weakauras and other stuff like plater profiles, etc. Basically it's users share addon configurations there which can be downloaded and used by the addons itself. They have their own update client if you don't mind to take a look, its nice but I would prefer to update everything with the same client.

**Comment by jliddev** [comment]
Yeah I'd say a separate issue for each bullet. Since they can be added and released separately. Makes issues easier to track.

I've never really used auras so I can take a look at that.

I can look into tsm as well.

**Comment by mspykerez** [comment]
As requested I opened separated tickets for this suggestions.
