### ISSUE TITLE
WoWUp doesn't rerender/resize properly when forcefully resized by external Apps

### ISSUE THREAD

**Issue by Sleaker** [jliddev/WowUp#105]
I use Windows PowerToys fancy zones functionality, and when moving WoWUp into a zone the window will get resized but the window will be completely white or completely black. minimizing and maximizing or closing to taskbar does not fix this issue.  Only closing and re-opening the app.  It would be nice if WoWUp worked with FancyZones method of resizing.

**Comment by jliddev** [comment]
This may seem like a strange request, but could you try to do the same thing with the 2.0 alpha and see if it works?

https://github.com/jliddev/WowUp/releases/tag/v2.0.0-alpha.7

**Comment by Sleaker** [comment]
Seems to be working properly in 2.0 alpha 7.

**Comment by jliddev** [comment]
Great :D
