### ISSUE TITLE
Show supported WoW version

### ISSUE THREAD

**Issue by sdousley** [jliddev/WowUp#107]
On the Twitch interface, you can see the supported wow version of an addon.

Seeing an addon with supported version 6.x, I might understand if it doesn't work with 8.3.0 for instance.

**Comment by jliddev** [comment]
The Game Version column represents the compatible version of an addon.

**Comment by sdousley** [comment]
Sorry, I should have been a little more clear, whilst you can see this AFTER it's installed, you can't see the game version or number of installs on the "Get Addons" tab like you can on Twitch/Curse etc.
