### ISSUE TITLE
Don't ask to update addons with a more recent version installed

### ISSUE THREAD

**Issue by walshta** [jliddev/WowUp#108]
Similar to issue #79, the client can't determine if the provider has the most recent version available. This is mostly a concern for addons like Raider.io that have multiple update streams. Patreon subscribers get updates more often than curseforge or wowinterface. For example I have version v202010071500 installed but CurseForge has v202010070600.

I know in this example its a date/time stamp version so its easy to know which is most recent in this case and that may not be true for all. 

![image](https://user-images.githubusercontent.com/7518381/95366602-a4a58580-08a1-11eb-8495-54b53bca233e.png)
![image](https://user-images.githubusercontent.com/7518381/95366698-c69f0800-08a1-11eb-887f-ffdab42537fb.png)

**Comment by jliddev** [comment]
If you're using another app to manage that particular addon you can right click and ignore it in wowup so it wont bug you about it. WowUp does not know if you change the folders outside the app unless you hit the 'Re-Scan Folders' button.
