### ISSUE TITLE
Installing addons

### ISSUE THREAD

**Issue by mspykerez** [jliddev/WowUp#11]
- Let us apply the channel (stable, beta, alpha) globally to all addons in addition to setting it up individually.
- Add option to auto-install outdated addons (when program starts and with checks every hour or so when game is or not running).
- Allow us to manually downgrade an addon to a old version.

**Comment by jliddev** [comment]
These should be split out into separate requests.

Global channel should be simple enough.

Auto-Update should be in the next update v1.14.0

Downgrading is non trivial and different per addon source so should be a separate issue.

**Comment by mspykerez** [comment]
OK I opened separated tickets for this suggestions.
