### ISSUE TITLE
WowUp doesnt install the right version for a client

### ISSUE THREAD

**Issue by TimothyLuke** [jliddev/WowUp#114]
Hi all, 

As a mod author I am getting a ton of support requests because WowUp keeps installing the wrong version of a mod.

I currently have the following clients installed:

- Retail  (8.3)
- Classic (1.13)
- Beta (9.0)
- PTR (9.0)

Each of these builds have different TOC settings and on Curse each build has an identified Game Version.
![image](https://user-images.githubusercontent.com/573717/95410613-fc102800-096b-11eb-8475-3211a15062c3.png)

Irrespective of the client - WowUp only wants to install the 8.3.0 version

**Comment by jliddev** [comment]
I am happy to look into this. Currently when i install it fresh through the app it installs 2.5.11. is that not the expected version? what are you seeing on your end?

Feel free to hit me up on discord @zakrn we can resolve it faster.

**Comment by TimothyLuke** [comment]
Classic should install 2.5.11-classic (or 2.6.01-beta5-Classic) as it’s 11305  but the beta and ptr should if I go to 2.6.01-beta5-shadowlands as they are set to 90002 instead of 11305.  If that makes any sense?
TimothyLuke

**Comment by TimothyLuke** [comment]
Works perfectly for retail just not any other client.

TimothyLuke

**Comment by jliddev** [comment]
For classic i have 2.5.11-classic, i am currently updating my ptr to give that a check. what version are you seeing for classic?

**Comment by TimothyLuke** [comment]
Getting this for Beta: 

![image](https://user-images.githubusercontent.com/573717/95413691-91fb8100-0973-11eb-82bf-a5e04e28106f.png)

This for Classic:
![image](https://user-images.githubusercontent.com/573717/95413707-9e7fd980-0973-11eb-8c2c-55fffe9bb507.png)

This for PTR
![image](https://user-images.githubusercontent.com/573717/95413729-a8094180-0973-11eb-8a6c-8d10ff792bf5.png)


Using 1.18.1

**Comment by jliddev** [comment]
PTR looks right
![image](https://user-images.githubusercontent.com/20467484/95416959-7ce20c00-08f9-11eb-9dc1-462d3a05f442.png)

**Comment by TimothyLuke** [comment]
that should be GSE-2.6.01-beta5-shadowlands as the client is game version 9.0

**Comment by TimothyLuke** [comment]
Curse also cant get this right themselves

**Comment by jliddev** [comment]
Your beta and classic folders are strange. is that by chance your addon development folder? If you dont mind could you go into the Options tab and hit the "Dump Debug Data" and send me the latest log file via the "Show Log Files" button?

**Comment by TimothyLuke** [comment]
[wowup-logs20201008.txt](https://github.com/jliddev/WowUp/files/5345408/wowup-logs20201008.txt)
That the file you need?

Those folders with the @project-version@ look like:
#@retail@
## Interface: 90001
#@end-retail@
#@non-retail@
# ## Interface: 11305
#@end-non-retail@

## Version: @project-version@

THey currently have manual dev code - I wanted to pull in the built stuff but not getting the correct builds

**Comment by jliddev** [comment]
Looking at the Curse API GSE-2.6.01-beta5-shadowlands is not even returned as an option so there's not much I can do on that one specifically.

**Comment by TimothyLuke** [comment]
You'd think by now there were "standards" for doing this 8-)

**Comment by jliddev** [comment]
That would be nice lol

**Comment by jliddev** [comment]
Looks like your issue with Classic and Beta is because it couldnt match anything from Curse based on the folder fingerprint due to edits, so it moved to the next provider which is WowInterface which does not support alpha/beta releases as far as i know.

Should have fallen back to the X-Curse-Project-ID tag first tho so looks like a bug there.

**Comment by jliddev** [comment]
This logic is all new in 2.0
