### ISSUE TITLE
improving the UI

### ISSUE THREAD

**Issue by mspykerez** [jliddev/WowUp#12]
- Add search addons by category and author.
- Right click/double click an addon to show full addon description, changelogs, screenshots and version history if available.
- Put a clickable link on the 'Porvider' column directing to the addon website.
- Put up to date addons and outdated addons on separated tabs.
- Put ignored addons on their own tab and let us update them manually if wanted.
- Add sorting options for columns and allow them to be toggle on/off the tabs.

- On 'My Addons' and 'Get Addons':
> Add a column with the addon category.
> Add a column with the short addon description of what does it do.
> Add a column with the addon size.
> Add a column with addon date created.
> Add a column with addon total downloads.
> Add a column with addon popularity.

- On 'My Addons':
> Add a column with the addon 'Provider'.
> Add a column with the installed version of the addon and respective released date. (could be done to separate columns as well: one for the installed version, and another for the installed version release date)
> Add the respective released date to the latest version column. (could be done to separate columns as well: one for the latest version, and another for the latest version release date)

-On 'Get Addons':
> Add a column with the game version supported by the addon.
> Add a column with the latest version of the addon and respective released date. (could be done to separate columns as well: one for the latest version, and another for the latest version release date

**Comment by jliddev** [comment]
Most of these are just optional columns and or sorting/filtering. Will probably wait to think about these until the cross platform version is ready

**Comment by mspykerez** [comment]
Yes! this is mostly all about new columns/tabs hence I referred to it as UI improvements.

**Comment by WybeBosch** [comment]
+1 for addon date created column, and also a column for last update date (helps seeing which of my addons are insanely old)

**Comment by jliddev** [comment]
A lot of these extra columns will probably get delayed until 2.0 columns in wpf are a bit of a pain but i'll keep this around.

**Comment by tomrus88** [comment]
Context menu in addon list that opens addon's website would be nice.

**Comment by Walkerbo** [comment]
> Context menu in addon list that opens addon's website would be nice.

Clicking on the addon title opens the addon website.

**Comment by cynthiawoodard** [comment]
+1 for sortable # of downloads column! it's really the only thing I find lacking in the app. Thanks for a great app, especially in light of the Overwolf/Curseforge news.

**Comment by jliddev** [comment]
A lot of these are complete in 2.0, feel free to create a [2.x] ticket for any more individual column requests.
