### ISSUE TITLE
[Alpha 2.0] missing "total addons" count in the right bottom

### ISSUE THREAD

**Issue by linaori** [jliddev/WowUp#122]
In the current stable (1.18.1) you can see the total addons installed
![image](https://user-images.githubusercontent.com/1754678/95843827-706e1100-0d48-11eb-9ffa-eaddeb5dd1de.png)

In v2.0.0-alpha.7 the addon count is missing
![image](https://user-images.githubusercontent.com/1754678/95843906-8bd91c00-0d48-11eb-9f7e-c3e55884b7f2.png)

I couldn't find the addon count anywhere else, so I'm assuming it was only added to `1.x`.

**Comment by jliddev** [comment]
Look for this in alpha.8
