### ISSUE TITLE
Request: sort addon list by recently updated

### ISSUE THREAD

**Issue by plottingCreeper** [jliddev/WowUp#124]
The second column in the addon list, status, sorts by which ones are up to date, and which ones are not. The twitch client in the same column would also show recently updated, so they could be sorted top of the list.
This way, it makes it quite easy to see which addons may be responsible for something breaking in game, without having to open the wowup log. 
Attached screenshot is of the twitch client, demonstrating the desired behavior. 
![Screenshot 2020-10-14 080851](https://user-images.githubusercontent.com/6550725/95904905-a49f0b80-0df4-11eb-88c3-71ba0bf9009a.png)

**Comment by jliddev** [comment]
Try out the new Released At column in 2.0 to see if it meets your needs.
