### ISSUE TITLE
Failure for one source to respond results in failure to load entire current addons list

### ISSUE THREAD

**Issue by ShadusDotCom** [jliddev/WowUp#126]
Tukui failed to respond, and put WoWUp in an eternal Loading Addons... loop.  It had successfully loaded the Curse addons internally, but displayed nothing.

`2020-10-13 16:40:52.094 -07:00 [ERR] Failed to get all addons
Flurl.Http.FlurlHttpException: Call failed. A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. GET https://www.tukui.org/api.php?addons=all`

[wowup-logs20201013.txt](https://github.com/jliddev/WowUp/files/5374774/wowup-logs20201013.txt)
![2020-10-13](https://user-images.githubusercontent.com/8230770/95928122-6f9fa400-0d75-11eb-86da-c906dca04fda.png)

**Comment by tombomb** [comment]
tukui is down

**Comment by promaori** [comment]
Looks like there's no error handling from the client POV to show that there were connection errors to Tukui - I only mention this as I'm getting connection issues with CurseForge as well.

**Comment by jliddev** [comment]
Put out a hotfix 1.18.2, give it a try.
