### ISSUE TITLE
Can not change addon folder path

### ISSUE THREAD

**Issue by Omaruhiro** [jliddev/WowUp#127]
The default settings for the wow client paths for retail and classic is reversed and it will not allow me to change it.
![image](https://user-images.githubusercontent.com/72841086/95930907-bdc49f80-0d95-11eb-98b2-217ca53929ed.png)

![image](https://user-images.githubusercontent.com/72841086/95930947-d634ba00-0d95-11eb-9e3c-cd368dd8dc1d.png)

**Comment by jliddev** [comment]
select the folder that contains _retail_ which looks right in your first image. The addon providers are down right now, so things may not appear.
