### ISSUE TITLE
'Re-Scan Folders' sometimes does not pick up all addons in folder

### ISSUE THREAD

**Issue by kulkuza** [jliddev/WowUp#128]
My addons:
![folder](https://user-images.githubusercontent.com/19176153/95934705-5f43f500-0d86-11eb-99a6-ca07c34f1367.PNG)

Bug:
![bug](https://user-images.githubusercontent.com/19176153/95934721-679c3000-0d86-11eb-9fd2-c9829793b543.PNG)

**Comment by kulkuza** [comment]
Same issue on v1.18.2. Also tried reinstalling addons. Looks like it is 1 in 3rd chance it may not show up all the addons.

**Comment by BloodDragon2580** [comment]
Have the same Problem. Not allö Addons will be showing.

**Comment by Heidric** [comment]
More than that, from re-scan to re-scan it picks up a random assortment of addons without any apparent correlation

**Comment by gman4** [comment]
I have 21 addons. Which were correctly recognized. But every time I check have less and less of them like 16, when 12.

**Comment by bthurlow** [comment]
Same issue here with 1.18.4.  Random selection of addons displayed without being the full list.  Have tried clearing cache as well as uninstall and reinstall of wowup.

**Comment by TopoDiFogna** [comment]
I also noticed that it loses the information on the preferred channel for some of the ones that are detected

**Comment by Xaemyl** [comment]
It also throws a dialog "Failed to scan for Wowinterface" or something like that.

**Comment by jliddev** [comment]
CurseForge api is still broken, you can try 1.19 beta where we created a workaround.

**Comment by MelchiorGaspar** [comment]
ok... 
but how is the CurseForge API broken?
I will stick with the v2.0 alphas for testing...
