### ISSUE TITLE
Clicking 'remove' only works on some addons

### ISSUE THREAD

**Issue by wheatbread** [jliddev/WowUp#130]
When I clicked 'remove' on 2 addons I had, they both disappeared from the display (and relaunching Wowup did not show them in the list).  But 1 of them was still there in the addon folder when I manually went and checked.

The addon that was removed was Corruption Tooltips, while the one that was still there was Adibags_CorruptionGear.

**Comment by jliddev** [comment]
This is a tricky one, depending who the provider you had it installed from i may or may not know every folder that was copied. its a slight bug in the app right now.

**Comment by jliddev** [comment]
New remove logic in 2.0
