### ISSUE TITLE
The re-scan folders gives error Failed to scan from TukUI

### ISSUE THREAD

**Issue by gman4** [jliddev/WowUp#131]
In the latest version gives this error every time
![01111](https://user-images.githubusercontent.com/45881730/95975701-2a37b100-0e1f-11eb-9d5e-d26c472698dc.jpg)

**Comment by Heidric** [comment]
TukUI website/API is down, so it's not really relevant

**Comment by Masumia** [comment]
That may be, but should the program stop looking for your addons at that point? I mean, this should be a warning, not an error. Due to this error, only a few of my addons are listed and I don't use TukUI.

**Comment by mkvlrn** [comment]
Main TukUI site still down but [their repo](https://git.tukui.org/elvui/elvui/-/tree/development) is up.

But... If I was to make a guess, I'd say they are _**very much against**_ someone scrapping their stuff to put on a "third party" add-on manager.

**Comment by animegirl13** [comment]
> But... If I was to make a guess, I'd say they are _**very much against**_ someone scraping their stuff to put on a "third party" add-on manager.
Not really their choice
https://parsers.me/us-court-fully-legalized-website-scraping-and-technically-prohibited-it/

**Comment by mkvlrn** [comment]
> Not really their choice
> https://parsers.me/us-court-fully-legalized-website-scraping-and-technically-prohibited-it/

Oh yeah! But what I mean is that... judging by the infamy surrounding the developers, I wouldn't put past them keeping their site offline just to prevent scraping.

Gotta keep that ad and "premium" $ coming!

**Comment by N6REJ** [comment]
close this please I don't need spam

**Comment by Masumia** [comment]
> 
> 
> close this please I don't need spam

You could just unsub from the notifications.

**Comment by mjgreer** [comment]
> 
> 
> > close this please I don't need spam
> 
> You could just unsub from the notifications.

this guy githubs

**Comment by N6REJ** [comment]
> > close this please I don't need spam
> 
> You could just unsub from the notifications.

yep, sure could.. I could kill notifications and miss anything else &/or things I've commented on myself.
I could even unwatch the project and not give a damn about where it goes.  After all thats the FOSS way isn't it?
OR someone could actually close an issue that isn't an issue.. .What a concept!

**Comment by JohnnyQuest1983** [comment]
> close this please I don't need spam

delete your comment please I don't need spam

Change your Watch settings you absolute clown

**Comment by jliddev** [comment]
What even happened here?
