### ISSUE TITLE
Re-scan folders is not recognizing correct local versions

### ISSUE THREAD

**Issue by norecha** [jliddev/WowUp#134]
Looks like re-scan doesn't reset local db properly. I would update an addon, re-scan, and it thinks it has the old version again, and prompts to update again.

I checked the .toc files locally and they are not matching what wowup is reporting. I may have a corrupted db from playing too much but shouldn't re-scan just rebuild the local index

**Comment by asdf12303116** [comment]
I think when network error ，sacn priority wrong。I try a few times resacn.  One addon report form 
different  provider.

The log maybe show this
[wowup-logs20201014.txt](https://github.com/jliddev/WowUp/files/5379359/wowup-logs20201014.txt)

**Comment by jliddev** [comment]
This looks to have been during the pre-patch window when all the providers were down.
