### ISSUE TITLE
Add-on is showing twice because each provider name is slightly different

### ISSUE THREAD

**Issue by raysmith59** [jliddev/WowUp#135]
Altoholic shows up twice for me, once for each provider, because the names on each are slightly different (Altoholic Retail vs Altoholic-Retail).  For now I'm ignoring one of them but it'd be nice to be able to consolidate them somehow (right-click -> Rename?).

**Comment by jliddev** [comment]
Technically this could be accurate. There's two Altoholics :(

**Comment by raysmith59** [comment]
Yes (the original, plus the Teelo fork), in this case Altoholic Retail and Altoholic-Retail are both the Teelo forks so they are literally the same add-on.
