### ISSUE TITLE
When first installed, set channel for each add-on based on the channel for the currently installed version

### ISSUE THREAD

**Issue by raysmith59** [jliddev/WowUp#136]
Enhancement request.  During first install when the database is created, check all channels against the installed version and set the add-on channel based on the installed version.  Won't give a perfect result but it'll be significantly better than having them all default to retail for those of us who use beta or alpha channels a lot.

**Comment by jliddev** [comment]
The ability to bring in the scanned channel type was added in 2.0 :D
