### ISSUE TITLE
WowUp is "updating" addons to old versions, and ignoring newer ones.

### ISSUE THREAD

**Issue by ultima98** [jliddev/WowUp#137]
Since the prepatch dropped, I've been getting issues where WowUp will either not detect any updates for addons that should have them, or detect an update, but "update" the addon with an older version, instead of the newer one(s).

Case in point: ElvUI had a 12.00 update available at prepatch launch, but WowUp still has not gotten the update to register, and I ended up having to manually install the update earlier today. In addition, DejaCharacterStats got an update, but WowUp decided to go BACKWARDS a version (from 900b1 to 830r306), and then do so AGAIN (from 830r306 to 830r305) when I manually scanned for updates, instead of updating the addon to the _correct_ version of 900r1.

This has been the case for many of my addons, and I'm now dealing with the headache of manually going through my addon list and checking the addon pages to see what's been updated correctly and what hasn't.

**Comment by animegirl13** [comment]
Can confirm this behavior. At first I thought it was because they were changing provider from curse to wowinterface but now I'm seeing a bunch of addons from curse also trying to update to older versions

**Comment by Catalyst8487** [comment]
I'm seeing this with WoWUp and the Twitch client so it may be API related and not necessarily WoWUp.

**Comment by mkvlrn** [comment]
> I'm seeing this with WoWUp and the Twitch client so it may be API related and not necessarily WoWUp.

Same thing with Ajour.

A few don't even get recognized, and if you install them again, nothing changes.

**Comment by Yama1291** [comment]
What happened to me is that the app downloaded an old version from wowinterface instead of the updated curseforge release.
Specifically for KUI Nameplates.

**Comment by Amanser** [comment]
> What happened to me is that the app downloaded an old version from wowinterface instead of the updated curseforge release.
> Specifically for KUI Nameplates.
> 
> https://i.imgur.com/b6ikTmM.png

Same issue here. It would be nice to be able to choose the provider where the addon comes from as wowinterface tends to be outdated.

**Comment by ultima98** [comment]
> > What happened to me is that the app downloaded an old version from wowinterface instead of the updated curseforge release.
> > Specifically for KUI Nameplates.
> > https://i.imgur.com/b6ikTmM.png
> 
> Same issue here. It would be nice to be able to choose the provider where the addon comes from as wowinterface tends to be outdated.

This is not the same issue.

**Comment by Amanser** [comment]
My issue is the same as Yama1291's. The second sentence of my reply was a suggestion.

**Comment by ultima98** [comment]
> My issue is the same as Yama1291's. The second sentence of my reply was a suggestion.
> 
> Edit: I just noticed that when I go to the Get Addons section and type "KUI" that KUI Nameplates appears with Curse as the provider. https://imgur.com/a/sLTJI39

I understand that you have the same issue as Yama1291. However, this thread is for a DIFFERENT issue. It's generally considered bad form to bring up a different bug in someone else's bug report, unless there's evidence to suggest that the two bugs are directly related.

Anyway, after trying to update my addons through both Cursebreaker AND the Twitch app, I have discovered that the issue is NOT specific to WowUp, and in fact appears to be an API issue.

**Comment by jliddev** [comment]
Since wowup uses a priority based list of addon providers and 2 of the providers were either down and or giving out bad data for most of the day im going to write this off as an unfortunate circumstance. It it persists feel free to reopen this.
