### ISSUE TITLE
WowUp will not start after updating to 1.18.4

### ISSUE THREAD

**Issue by robertjamesftw** [jliddev/WowUp#138]
WowUp was working fine yesterday and this morning, and I got a message indicating an update was available. I fired that off, and the app updater started working. I got the "restart" button, and I clicked that. But now the app will not come up. There's no error message, it just won't initiate. I'm running Win 10 Home. What other information can I get for you?

**Comment by jliddev** [comment]
Had a couple reports of this after last nights windows update. 

You might try finding any wowup errors in the event viewer and report back.

https://www.howtogeek.com/123646/htg-explains-what-the-windows-event-viewer-is-and-how-you-can-use-it/

**Comment by robertjamesftw** [comment]
I just ran the Update process again, to see if I could capture the issue. I found this in the Event viewer:

Application: WowUp.exe
CoreCLR Version: 4.700.20.47201
.NET Core Version: 3.1.9
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TypeInitializationException: The type initializer for 'System.Windows.Application' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'System.Windows.Navigation.BaseUriHelper' threw an exception.
 ---> System.BadImageFormatException: Could not load file or assembly 'System.Linq, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Format of the executable (.exe) or library (.dll) is invalid.
File name: 'System.Linq, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.IO.Packaging.PackUriHelper.EscapeSpecialCharacters(String path)
   at System.IO.Packaging.PackUriHelper.Create(Uri packageUri, Uri partUri, String fragment)
   at System.IO.Packaging.PackUriHelper.Create(Uri packageUri)
   at System.Windows.Navigation.BaseUriHelper..cctor()


   --- End of inner exception stack trace ---
   at System.Windows.Navigation.BaseUriHelper.get_PackAppBaseUri()
   at System.Windows.Application.ApplicationInit()
   at System.Windows.Application..cctor()
   --- End of inner exception stack trace ---
   at System.Windows.Application..ctor()
   at WowUp.WPF.App..ctor()
   at WowUp.WPF.App.Main()

**Comment by robertjamesftw** [comment]
Attempted to run WowUp.exe in this state, just to capture the event:

Fault bucket 2259886764925253735, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: WowUp.exe
P2: 1.18.4.0
P3: 5f6b3998
P4: KERNELBASE.dll
P5: 10.0.19041.488
P6: 5b4a3325
P7: e0434352
P8: 0000000000023e49
P9: 
P10:

**Comment by robertjamesftw** [comment]
I've recovered to the .BAK version in order to restore function. Which, by the way, I very much appreciate how you did the update, as it allows me to roll back painlessly.

**Comment by robertjamesftw** [comment]
On a whim, I decided to download v1.18.4 directly, rather than run the update process, on the chance that the issue was somewhere in that process, rather than in the .EXE file, but the end result was the same: a crash, as I listed above.

**Comment by jliddev** [comment]
I would ask you to try the 2.0 version. Im not finding any info for that type of error outside of very old WPF on old .net article.

**Comment by robertjamesftw** [comment]
Using 2.0-alpha14, and it's working well. I'll close this issue.
