### ISSUE TITLE
Multi select context menu options

### ISSUE THREAD

**Issue by jliddev** [jliddev/WowUp#139]
Multi select is in, just need to swap out the context menus when theres more than one selected.

Current Options:
  Title: 
```
selectedItems.Count() > 1
               ? $"{selectedItems.Count()} addons selected"
               : string.Empty;
```
AutoUpdate checkbox

Channel submenu:
- Stable checkbox
- Beta checkbox
- Alpha checkbox

Re-Install
Divider
Remove

**Comment by mrchops1024** [comment]
@jliddev send this my way

**Comment by jliddev** [comment]
This is complete.
