### ISSUE TITLE
Column Game Version does not update

### ISSUE THREAD

**Issue by bscheutjens** [jliddev/WowUp#140]
When I update an addon from 8.* to 9.*, the column Game Version does not update. I've verified this by opening the .toc file, which now states the addon support 9.0.1, but in WowUp it still shows as 8.0.1. Restarting WowUp does not help.

I do not want to rescan my folders, beacsue of an other issue (already reported by somebodey else) which might casue addons to disappear from the list.

**Comment by jliddev** [comment]
There were issues related to Game Version fixed in 2.0, coming soon :)
