### ISSUE TITLE
WoWup not detecting all of my addons for either retail or classic..

### ISSUE THREAD

**Issue by MelchiorGaspar** [jliddev/WowUp#144]
title says it all.. but when I click the re-scan button it some times finds other addons and forgets some... its rather frustrating...
instead it should reading the contents of the addon folders on startup and refresh like the Twitch Client does...

sry but your addon manager still needs a lot of work... lol ;-)

**Comment by Excelis** [comment]
I have the same issue.  But I'll try to be more helpful.  I'm not seeing the following:
Answering_Machine, AutoBar, BankStack, Clique, Decursive, DiscordUnitFrames, GTFO, SmartBuff, Skillet, and TipTac.  There may be others that I missed.

Is it provider related?  Also, there anyway to set the provider for a specific addon?

**Comment by jliddev** [comment]
We were able to figure out why users get random numbers of addons detected last night. The issue is with CurseForge's API not WowUp. We're brainstorming ways to mitigate confusion in the future.

**Comment by MelchiorGaspar** [comment]
> 
> 
> We were able to figure out why users get random numbers of addons detected last night. The issue is with CurseForge's API not WowUp. We're brainstorming ways to mitigate confusion in the future.

ooh ok thx for the heads up... I look forward to a fix if u can...

**Comment by Heidric** [comment]
Duplicate of #128

**Comment by MelchiorGaspar** [comment]
> 
> 
> Duplicate of #128

ooh.. ops I missed that then sry... I will close this then...
