### ISSUE TITLE
Author/Provider Column overlapping and Author cell need overflow ellipsis

### ISSUE THREAD

**Issue by Cratis1831** [jliddev/WowUp#145]
![](https://cdn.discordapp.com/attachments/766027708819570689/766396371145195531/unknown.png)

![](https://cdn.discordapp.com/attachments/766027708819570689/766396508672229436/unknown.png)

**Comment by mrchops1024** [comment]
@Cratis1831 It looks like authors are wrapping properly, so I'm not sure what the ellipsis would accomplish. Did you have a different idea on how you think the data should be presented?

**Comment by Cratis1831** [comment]
@mrchops1024 essentially once the author column hits a certain amount of characters the text should add the ellipsis so the rows are all the same height
