### ISSUE TITLE
addons not being detected

### ISSUE THREAD

**Issue by bloodchops** [jliddev/WowUp#151]
so when I use this it keeps saying different numbers of addons in the folder. Does it not find them all?

**Comment by Kvasi** [comment]
Same happens for me, every time I press rescan folder it's a different number, 25, 44, 42, 46.

**Comment by DoctorBak** [comment]
Same. I tried with admin priviledges but it still shows the wrong number of addons

**Comment by jliddev** [comment]
We were able to figure out why users get random numbers of addons detected last night. The issue is with CurseForge's API not WowUp. We're brainstorming ways to mitigate confusion in the future.
