### ISSUE TITLE
ctr+A in Alfa

### ISSUE THREAD

**Issue by Barthezzcz** [jliddev/WowUp#157]
U cant select all via ctrl+A in the latest alfa ver. Shift click to select multiple items works but it applies on for one item in the selection and it will highlight the text as follows 

![image](https://user-images.githubusercontent.com/67265871/96333308-59d9f980-1069-11eb-81ab-fe9e7ec0149e.png)

**Comment by jliddev** [comment]
This should be working as of Alpha 11.
