### ISSUE TITLE
wowup wants to update addons if they do not match the 'latest' version, even if they are newer version #s

### ISSUE THREAD

**Issue by panoplybez** [jliddev/WowUp#158]
I've noticed that for addons where I have manually updated them to newer versions, wowup wants to 'update' them to whatever matches the 'latest' version on curse, even if that is in fact an older version # than what I have installed. Examples: TitanPanel shows installed version 5.19.0.90001a, but wowup wants to update it to 5.18.7.80300. (and yes, I have wowup set to look at the alpha channel for this).

**Comment by Barthezzcz** [comment]
yep, its fixed in the latest beta

**Comment by jliddev** [comment]
Newer is relative. There's no way to use the version number to derive meaning simply because there is no standard. If curse has an 'older' version but it's the latest that's what WowUp will show what curse says is correct.
