### ISSUE TITLE
wowup not recognizing some addons

### ISSUE THREAD

**Issue by panoplybez** [jliddev/WowUp#159]
wowup isn't seeing that I have certain addons installed, whereas twitch client still sees them. I also have a feeling wowup seems to be losing the fact that I have them installed if I have modified the files in any way. I have done a few re-scan folders, but that doesn't help - they still don't appear in My Addons list.

wowup is missing - (retail)
Garrison Mission Manager
Decursive
Gnosis
Long Macros
Outfitter
Rarity
SoDWhisper

**Comment by panoplybez** [comment]
oops sorry, I found older issues about this. Is it the same problem? something with the curseforge API?

**Comment by Potsrabe** [comment]
Hello same problem here with:
AchievementsReminder

AddOn is installed under retail, but in WOWUP missing, so I have to update it manually from Curse.

**Comment by jliddev** [comment]
CurseForge API is still broken, give the 1.19 beta or the 2.0 alpha a try, it uses a different method.
