### ISSUE TITLE
[2.x] Improving visual accessibility by adding zoom

### ISSUE THREAD

**Issue by linaori** [jliddev/WowUp#160]
From Discord:

> Catitude Today at 10:32 AM
This is a very sincere request: I am vision impaired & I just installed WowUp as a possible replacement for Twitch...
On my 34" Ultra Wide Monitor it's difficult for me to use it :frowning:  Night blind (dim light vision impaired) as well as needing giant fonts on my (white) keycaps & my screens (I read paperbacks 8" from my nose) & we couldn't find any option for a white/light background or font resize or zoom. Maximizing the window didn't change the size of the font either.
Oh and thank you

I've played around a bit by dropping a snippet in `main.ts` and it worked, though it needs some restrictions and probably a save in the wowupservice settings to ensure next time the zoom will still be correct. This functionality works with ctrl+scroll, just missing the ctrl+0 to reset the zoom level to 100%. Additionally we could show the current zoom level in the bar also showing the version, with a hover how to change it. 

I currently have no idea what the best location would be to put this code, nor if the snippet (below screenshots) I used is the "correct" code, I've just grabbed it from google. If someone has pointers on where to put it, I could probably build it myself.

![image](https://user-images.githubusercontent.com/1754678/96363484-ff0dd400-1134-11eb-8728-61b0189216fa.png)
![image](https://user-images.githubusercontent.com/1754678/96363488-059c4b80-1135-11eb-9371-83683f860827.png)

```typescript

const electron = require('electron');
const BrowserWindow = electron.remote.BrowserWindow;
let win = BrowserWindow.getFocusedWindow();

win.webContents.setZoomFactor(1.0);

win.webContents
  .setVisualZoomLevelLimits(1, 5)
  .then(() => console.log('Zoom Levels Have been Set between 100% and 500%'))
  .catch((err) => console.log(err));

win.webContents.on('zoom-changed', (event, zoomDirection) => {
  console.log(zoomDirection);
  let currentZoom = win.webContents.getZoomFactor();
  console.log('Current Zoom Factor - ', currentZoom);
  console.log('Current Zoom Level at - ', win.webContents.zoomLevel);

  if (zoomDirection === 'in') {
    win.webContents.zoomFactor = currentZoom + 0.2;
    console.log('Zoom Factor Increased to - ', win.webContents.zoomFactor * 100, '%');
  }
  if (zoomDirection === 'out') {
    win.webContents.zoomFactor = currentZoom - 0.2;
    console.log('Zoom Factor Decreased to - ', win.webContents.zoomFactor * 100, '%');
  }
});
```

**Comment by jliddev** [comment]
Added in #161
