### ISSUE TITLE
[Alpha 11] Checking for add-ons and updating them does not show status or completion

### ISSUE THREAD

**Issue by Braxusz** [jliddev/WowUp#167]
With this new version, when I scanned for updates upon reopening, it found updates. I clicked 'update all' to install them, but no status change or progress was shown.  If I performed a re-scan for updates, the installation(s) had taken place, it just didn't show it.

This issue persists through an application quit and restart as well.

**Comment by jliddev** [comment]
Should be fixed in the next beta release
