### ISSUE TITLE
uninstalling addons

### ISSUE THREAD

**Issue by mspykerez** [jliddev/WowUp#18]
Allow uninstalling addons completely removing them from the wow addon folder and add an option to clean up the SavedVariables on WTF folder when uninstalling addons or when it detects a library of an addon that it's not present on the wow addon folder.

**Comment by jliddev** [comment]
When uninstalling it should already remove the folders from the interface folder, if not it's a bug.

Research required for identifying WTF items.

**Comment by jliddev** [comment]
Currently there are no plans to touch the WTF, gonna close this as the first part is complete.
