### ISSUE TITLE
Things which need localization

### ISSUE THREAD

**Issue by Medoke** [jliddev/WowUp#192]
### **Addons (need multi-language plural workaround):**
![3](https://user-images.githubusercontent.com/72464426/96651130-d22c0d80-133c-11eb-8fb2-f8f750c6f549.png)
### **Loadings:**
![4](https://user-images.githubusercontent.com/72464426/96651123-d0624a00-133c-11eb-9874-9266c4d43fe1.png)
### **Results (need multi-language plural workaround):**
![5](https://user-images.githubusercontent.com/72464426/96651124-d0fae080-133c-11eb-9b4f-3ec3a3ef58d3.png)
### **This tiny thing :)**
![1](https://user-images.githubusercontent.com/72464426/96651127-d1937700-133c-11eb-8397-07852f848ec0.png)
### **Re-scan button confirmation popup:**
![2](https://user-images.githubusercontent.com/72464426/96651129-d22c0d80-133c-11eb-9016-09817655ae76.png)
### **Such things in Options:**
![6](https://user-images.githubusercontent.com/72464426/96651126-d0fae080-133c-11eb-93f2-bfafd707ac6e.png)
![7](https://user-images.githubusercontent.com/72464426/96651897-76fb1a80-133e-11eb-841f-b8b139eca3d4.png)

Hope I didn't miss anything :)

**Comment by Medoke** [comment]
### **This one hard to catch :D there things to translate and bug fix naming:**
![зображення](https://user-images.githubusercontent.com/72464426/96652872-84190900-1340-11eb-9f09-b2f8870a40fd.png)

**Comment by Medoke** [comment]
### **Thanks to @Linaori that I got an addon to delete it and discover this window exists and need translation :D**
![зображення](https://user-images.githubusercontent.com/72464426/96919852-0a565c00-14b5-11eb-9b33-944ce4fc99bd.png)

**Comment by linaori** [comment]
I'll be going through the application today and try to find as many missing translations as possible

**Comment by jliddev** [comment]
I think this is complete
