### ISSUE TITLE
Mods not showing.

### ISSUE THREAD

**Issue by Kirbdawg** [jliddev/WowUp#196]
I notice Addons disappearing from Wowup.   Since the prepatch, I've been modifying/hacking addons to temporarily get them working.  I'm thinking you use some kind of checksum to verify addons.  And, if I modify one, it disappears because the checksum is no longer valid.   Like Twitch, it'd be nice to show a status of "modified" rather than it completely disappearing from view.

**Comment by jliddev** [comment]
This is being worked on, but is a duplicate
