### ISSUE TITLE
Addons from retail PTR do not show up

### ISSUE THREAD

**Issue by joao44289** [jliddev/WowUp#2]
[wowup-logs20200707.txt](https://github.com/jliddev/WowUp/files/4885441/wowup-logs20200707.txt)

**Comment by jliddev** [comment]
v1.2.2 should properly validate the selected folder for WoW now.

**Comment by joao44289** [comment]
[wowup-logs20200707.txt](https://github.com/jliddev/WowUp/files/4885658/wowup-logs20200707.txt)

**Comment by joao44289** [comment]
[wowup-logs20200707.txt](https://github.com/jliddev/WowUp/files/4885822/wowup-logs20200707.txt)

**Comment by jliddev** [comment]
well that change didnt help much lol
