### ISSUE TITLE
Says there is no newer version, but there is one.

### ISSUE THREAD

**Issue by DaBear78** [jliddev/WowUp#201]
The tool says Overachiever has no newer version (shows 1.0.9 as newest version) and source is WowInterface. But there is a newer version (1.1.0) on Curse / Twitch. Is there any way to make your great tool to check all possible available sources for an addon?

**Comment by jliddev** [comment]
The latest version on WowInterface is list as 1.0.9 https://www.wowinterface.com/downloads/info11361-Overachiever.html if you want WowUp to scan all sources again, you can hit the re-scan folders button.
