### ISSUE TITLE
Installed addons with an update should have the action update instead of install.

### ISSUE THREAD

**Issue by penicaudm** [jliddev/WowUp#21]
Installed addons with an available update have the status "Install" but I believe the action should be update, as it can create a confusion whether your addon is installed or not.

**Comment by jliddev** [comment]
There have been a couple suggestions about renaming the "install" button on the my addons page. I believe the consensus was to rename it to "Register" in the hopes that it would be less confusing. Also planning to add a first run window explaining and/or an FAQ section to the website.

**Comment by Jeppeskovsgaard** [comment]
"Register" makes sense. An even better option would be for WowUp to register found addons as part of the scanning process, so the user won't ever see that option.
