### ISSUE TITLE
[2.x] Startup with system

### ISSUE THREAD

**Issue by jliddev** [jliddev/WowUp#214]
Create a toggle to allow the app to start when the system starts.

**Comment by Noxis-source** [comment]
Bonks!

**Comment by ayell** [comment]
Hi
I wanted to start doing it tomorrow, have you already started? Do you want me to do it?

**Comment by jliddev** [comment]
Why doesn't this comment show up on GitHub lol

**Comment by Noxis-source** [comment]
I pretty much got it working. Just need some actual tests to make sure that everythin works as expected. I wanted to PR it later today.

 I am a newbie in electron however. I do not think it is a bad idea to have two different implementations for that.

**Comment by ayell** [comment]
I don't understand why this one is displayed I didn't send it ... When I've seen your commits and your progress I prefer to let you finish and on my side finish the backup with a job every day (if the user wants) and see if it's possible to use a dropbox/google drive to externalize.

**Comment by jliddev** [comment]
Completed
