### ISSUE TITLE
(MacOS) ELVUI does not update on v2.0.0-alpha.14

### ISSUE THREAD

**Issue by seathasky** [jliddev/WowUp#224]
As title says. Elvui has stopped updating on the latest alpha for MacOS. Haven't been able to update ELVUI since getting the Alpha 14 release of WoWUp.. I'm currently on version 12.05 of Elvui and 12.06 is out. ELVUI use to update on alpha 12/13 so not sure what changed between test releases. I know this is not an ELVUI issue as my wife is on windows and just updated to 12.06 with the WoWup Microsoft Windows client v.1.19.1 (as seen in camera shot below) Just thought i'd chime in and let the devs know.

**my alpha client**
![Screen Shot 2020-10-24 at 9 22 38 PM](https://user-images.githubusercontent.com/17598024/97096793-13733480-163f-11eb-9507-fadda693e92a.png)

**elvui website:**
![Screen Shot 2020-10-24 at 9 20 13 PM](https://user-images.githubusercontent.com/17598024/97096775-becfb980-163e-11eb-81c4-12debf82fc26.png)

**my wifes windows client updated**
![PXL_20201025_012934733](https://user-images.githubusercontent.com/17598024/97096855-1de1fe00-1640-11eb-8cb5-31b838040668.jpg)

**Comment by seathasky** [comment]
Wierd! I guess you guys fixed it? 
![Screen Shot 2020-10-24 at 11 55 30 PM](https://user-images.githubusercontent.com/17598024/97098550-791deb80-1654-11eb-81d1-c58ff01ec5aa.png)

**Comment by jliddev** [comment]
Unfortunately nothing has changed with the TukUI provider :/

**Comment by seathasky** [comment]
Odd. Wonder why it took 4 days to show. I was updating regularly so no idea

**Comment by jliddev** [comment]
If it happens again let me know.

**Comment by seathasky** [comment]
Will do
