### ISSUE TITLE
Support modified/in development addons 

### ISSUE THREAD

**Issue by Walkerbo** [jliddev/WowUp#225]
When I have to edit a lua file to get it working again, 90001 broke so many addons that community users provided fixes before the author provided an updated version.

Any edited addons disappear from the list of installed addons, and the only way to bring them back is to reinstall which then breaks it again.

If the addon is installed but edited could it still be displayed as installed, even if the version is different.

I also have an addon that I am developing, it has a working toc and works in-game.
The Twitch app does display it and It would also be helpful it also be listed using the toc for the name even though it is not on any of the repositories.

**Comment by linaori** [comment]
There are some ideas on how to properly solve this, though nothing concrete has been come up with yet afaik as it's a bit more complex to solve. This issue also relates to #71 though I'm not sure it solves the same problem.

**Comment by jliddev** [comment]
Dump in with #71
