### ISSUE TITLE
Update All crash

### ISSUE THREAD

**Issue by Maev81** [jliddev/WowUp#23]
When doing Update All 2 addons show installing and the program crashes and at least one of the addons is updated

Next run the same thing, 2 addons being updated and crash even if they different addons from the first crash

If i click manually on all the buttons to update the addons no crash occurs

Windows 10 Pro 2004 x64 fully updated

**Comment by jliddev** [comment]
Mind giving me your latest log file? Either on here or DM it to me in Discord?

**Comment by Maev81** [comment]
Didn't know where they were, found it

[wowup-logs20200816.txt](https://github.com/jliddev/WowUp/files/5081154/wowup-logs20200816.txt)

**Comment by jliddev** [comment]
Could you try this again with the latest version? i made some changes to where i think the issue might be.

**Comment by Maev81** [comment]
Still the same

[wowup-logs20200817.txt](https://github.com/jliddev/WowUp/files/5085801/wowup-logs20200817.txt)
