### ISSUE TITLE
[1.19.1] All Addons Need Update After Upgrade

### ISSUE THREAD

**Issue by ldrewdavis** [jliddev/WowUp#237]
Had the previous version installed.  Updated a couple of adds as usual, then noticed the banner across the top of the app announcing a WowUp update (to 1.19.1).  Sure, why not?  Update downloaded, installed, restarted smoothly.  Then, upon scanning the directory, the app decided that everything in my list of addons needed to be updated, even though I'd just updated them.  Unexpected behavior, at least to me.  No ill effects to unnecessarily overwritten addons so far as I know (WoW's been down after today's update), but it wastes a bit of time and network bandwidth.

**Comment by linaori** [comment]
There has been a change in addon detection, causing this to happen. By using the "re-scan" button in the top right it should be fixed.
