### ISSUE TITLE
Column Sorting

### ISSUE THREAD

**Issue by jliddev** [jliddev/WowUp#26]
Add Sorting to columns

**Comment by Hillgrove** [comment]
to expand on this, I'd like to add column sorting (or even better filters) to the "Get Addons" page.

Curseforge has keywords for each addon telling if it's a map addon, raid addon etc those would be great.

# of downloads, last updated, which game version etc would all be welcome info

(im an info addict) :P

**Comment by jliddev** [comment]
Column sorting and basic filtering now added. Use the other UI issue for more suggestions :)
