### ISSUE TITLE
[2.x] Active tab losing brightness when clicking somewhere else [bug]

### ISSUE THREAD

**Issue by Medoke** [jliddev/WowUp#274]
https://www.youtube.com/watch?v=MFnHIlh8v64

**Comment by jliddev** [comment]
Im not sure this is a bug, the material control does this https://material.angular.io/components/tabs/overview

**Comment by Medoke** [comment]
Well, maybe it's angular bug, but in my opinion it's strange that active tab text losing brightness after click anywhere else 🤔

**Comment by jliddev** [comment]
marking as wontfix for now, so we dont fight the material css any more than we have to.
