### ISSUE TITLE
[2.x] Make the Select Wow Client Path Smarter

### ISSUE THREAD

**Issue by jliddev** [jliddev/WowUp#279]
If the user selects a nested inside the correct wow path, figure it out for them.

**Comment by pachei** [comment]
Not sure if this requires a new thread, seems to fit here. The path to WoWClassic.exe is in the "_classic_" folder, but selecting that folder throws up an error that it wants an extra nested "_classic_" folder. This is on Linux.

eg ~/World of Warcraft/_classic_/_classic_/WoWclassic.exe

**Comment by jliddev** [comment]
Changed in next build
