### ISSUE TITLE
[2.x] Update All Button not disabled on "My Addons" Page for different Clients

### ISSUE THREAD

**Issue by Cratis1831** [jliddev/WowUp#285]
Seems the "Update All" disabled function doesn't work on all Clients/Channels

My Addons Page (Retail):
![image](https://user-images.githubusercontent.com/1056561/97776787-9b76a400-1b41-11eb-8492-7efbcd47ad37.png)

My Addons Page (Beta):
![image](https://user-images.githubusercontent.com/1056561/97776803-b1846480-1b41-11eb-97e2-8dc49b217121.png)

**Comment by jliddev** [comment]
Fixed for next build
