### ISSUE TITLE
[2.x] Command line option to update addons and close immediately

### ISSUE THREAD

**Issue by WerDei** [jliddev/WowUp#287]
Always running the app in the background seems a bit overkill to me.
The option would allow for possibility to, for example, update the addons when WoW is launching or sheduling it to only run once a day.

(It seems that the 1.x version had a -q flag that did exactly that, but it doesn't work in 2.x)

**Comment by daemuth** [comment]
Is this supposed to work right now? I have attempted to start WoWUp with `-quit` and `-hidden` and combinations thereof, but couldn't get it to work. Win 10, WoWUp v2.7.1-beta.2  

Also couldn't find any documentation about this feature, if it exists.
