### ISSUE TITLE
[2.x] german locale problem? or strange number

### ISSUE THREAD

**Issue by Barracuda666** [jliddev/WowUp#290]
Maybe its a locale error:
billion is not Billionen in german, but Milliarden.
If it is a german Billionen it would be  10^12
a billion (=milliarde) is 10^9

anyways i find the written word in that column weird. short would be fine, i think

![image](https://user-images.githubusercontent.com/27134216/97788551-0499fe00-1bba-11eb-9a59-f52245f5139d.png)

**Comment by jliddev** [comment]
Complete.
