### ISSUE TITLE
[2.x] Missing installed addons in catalog

### ISSUE THREAD

**Issue by strayge** [jliddev/WowUp#292]
Now `Get Addons` tab completely hide installed addons.

Both `Twitch` and `Ajour` apps shows installed addons with `Up to Date` / `Installed` statuses.

Current behavior a bit confusing (especially for new users migrated from `Twitch` client).  

![image](https://user-images.githubusercontent.com/2664578/97789841-dece2280-1bd4-11eb-9452-915ddf48e9c3.png)

**Comment by Noxis-source** [comment]
Can we have an option to enable/disable this instead? I kind of got used to what it was before and my heart skips a beat when I see my installed addons there.
