### ISSUE TITLE
[2.x] JS Error on recovery from System Tray

### ISSUE THREAD

**Issue by robertjamesftw** [jliddev/WowUp#298]
Running 2.00-beta-1 on Win 10 Home 64. Works fine, except for when I try to bring the app back up by clicking on the system tray icon. 

![WowUp_beta_2 0_JSerror](https://user-images.githubusercontent.com/41345594/97819053-222b9e00-1c74-11eb-8227-3b3fb1d724da.png)

**Comment by jliddev** [comment]
Fixed for next release
