### ISSUE TITLE
Wowup spies on it's users

### ISSUE THREAD

**Issue by torkus** [jliddev/WowUp#3]
Why the spying, buddy? https://github.com/jliddev/WowUp/blob/master/WowUp.WPF/Services/AnalyticsService.cs

**Comment by jliddev** [comment]
Im not sure i would consider sending a made up number and your operating system "spying". I only use it to get a handle on how many people use it. I am happy to add an opt-out button.

**Comment by torkus** [comment]
>  I only use it to get a handle on how many people use it.

yeah, nah, that's spying ;) how about opt-in? if you're upfront and honest about why you want to track a person with a simple dialogue on first installation then you're much more likely to gain their trust.

If you use Github releases you can see the number of downloads via the api. There is also this handy webservice: https://somsubhra.com/github-release-stats/?username=jliddev&repository=wowup

**Comment by jliddev** [comment]
I have no problem making it opt in, I'll try and get it in the next version.

**Comment by jliddev** [comment]
Latest version now has a telemetry opt in prompt, if no objections. will close issue.

**Comment by torkus** [comment]
Cheers, @jliddev

**Comment by jliddev** [comment]
Strongbox is after me? :P

**Comment by torkus** [comment]
> Strongbox is after me? :P

Not at all, my list is called [comrades](https://github.com/ogri-la/wowman-comrades) and not 'competition' for a reason ;)

I sympathise with wanting to know more about who is using our programs (or what operating systems they are using, or where in the world they live, or what features they are using, etc) but collecting it without their knowledge and permission is noxious anti-social behaviour in my opinion.

You didn't have to make it opt-in and you expended extra effort to do so. Well done. :heart:
