### ISSUE TITLE
A New version of WowUp is available!

### ISSUE THREAD

**Issue by Vexxiwow** [jliddev/WowUp#34]
When I click the download button at the top of the interface it starts the download and changes to "restart". When I click the restart button, it restarts the program and it changes back to a "download" button and I am caught in a loop without the program actually updating.

**Comment by jliddev** [comment]
What version of the app are you trying to update ?

**Comment by Vexxiwow** [comment]
bottom right says v1.14.10.0 (for current version, I guess). I don't know what it tries to update to. I see there are 1.14.11 and 1.14.12 versions but my suggestion at the top of the interface does not say

**Comment by Vexxiwow** [comment]
should I re-install it from wowup.io?

**Comment by jliddev** [comment]
let me try something , it should work :/

**Comment by jliddev** [comment]
If you go to options, can you send me your latest log file? I was just able to update from 1.14.10 without an issue.

**Comment by Vexxiwow** [comment]
[wowup-logs20200823.txt](https://github.com/jliddev/WowUp/files/5142919/wowup-logs20200823.txt)
[wowup-logs20200826.txt](https://github.com/jliddev/WowUp/files/5142920/wowup-logs20200826.txt)
[wowup-logs20200827.txt](https://github.com/jliddev/WowUp/files/5142921/wowup-logs20200827.txt)
[wowup-logs20200828.txt](https://github.com/jliddev/WowUp/files/5142922/wowup-logs20200828.txt)
[wowup-logs20200820.txt](https://github.com/jliddev/WowUp/files/5142923/wowup-logs20200820.txt)
[wowup-logs20200821.txt](https://github.com/jliddev/WowUp/files/5142924/wowup-logs20200821.txt)

**Comment by Vexxiwow** [comment]
System.UnauthorizedAccessException: Access to the path is denied.

I don't know why the access is denied.

**Comment by jliddev** [comment]
That is weird, is the exe or the folder marked read only?

**Comment by Vexxiwow** [comment]
So, first. The application is installed in a different than the folder where the log files are, no idea how or why.
The application is not marked read only.
The folder where the "AddonBackups" / "Downloads" / "Logs" are is marked read-only and I cannot change that. When I click it, it asks me if I want to apply changes to this folder, subfolders and files, I click yes and it doesn't take.
I am on an admin account.

**Comment by jliddev** [comment]
well all the app data is stored in the %LOCALAPPDATA% route, updating doesnt need that folder just the one the exe is in.

**Comment by Vexxiwow** [comment]
The folder where the exe is in is marked Read-only but the exe itself is not.

**Comment by jliddev** [comment]
you can try making that not readonly. If that doesnt work you can just overwrite the exe with the latest from the website its the same difference. not sure whats up with the access.

**Comment by Vexxiwow** [comment]
Ok, I will overwrite it, thanks for your help.

**Comment by tordenflesk** [comment]
Same issue with upgrading from 1.15.0.b4

**Comment by jliddev** [comment]
Working on fixing upgrade issues, will use an updater app like a normal person.

**Comment by jliddev** [comment]
If anyone has this issue which is likely common now. Please try the latest pre-release and let me know if it works.

**Comment by jliddev** [comment]
This should be hopefully fixed in 1.16.0
