### ISSUE TITLE
[2.x] Make 2 things translatable ;)

### ISSUE THREAD

**Issue by Medoke** [jliddev/WowUp#341]
### **Addons selected**
![1](https://user-images.githubusercontent.com/72464426/98230595-ffdf9c00-1f63-11eb-9487-fd5a33763e74.png)
### **Go to**
![2](https://user-images.githubusercontent.com/72464426/98230597-00783280-1f64-11eb-96de-6fd1cf2eb9ca.png)

**Comment by jliddev** [comment]
fixed
