### ISSUE TITLE
[2.x] Classic addons do not show up under linux

### ISSUE THREAD

**Issue by codyf86** [jliddev/WowUp#348]
Classic addons do not show up / it says there aren't any, using Linux, even resetting the WoW folder in options.

Retail and Retail PTR addons show up just fine.  Seems like it might just be a typo somewhere since the other 2 work just fine.

**Comment by jliddev** [comment]
Addon fingerprints do not appear to be being calculated correctly, but only on linux.

**Comment by jliddev** [comment]
This looks to be related to path casing mismatches by the addon authors. should be fixed next beta.

**Comment by codyf86** [comment]
Yeah looks like _classic_ was originally created as the directory named Addon, when WowUp looks for the folder AddOn.  I fixed it manually on my side just renaming the directory.
