### ISSUE TITLE
WowUp showing 2 versions of same addon installed - curse/wowinterface

### ISSUE THREAD

**Issue by panoplybez** [jliddev/WowUp#351]
As of today, for some reason in My Addons I am seeing duplicates of an addon, one appears to be sourced from Curse (the one I had originally) and the other is showing sourced from Wowinterface. 
Its another bug (that I think you addressed in beta maybe) that the first addon won't properly show it has been updated, even after updating it several times.  The version # isn't correct on the left side.

![image](https://user-images.githubusercontent.com/52841691/98370470-9a91b680-2008-11eb-8ee7-79ce5e6fb76d.png)

**Comment by panoplybez** [comment]
Update - I downloaded and installed the Beta version of the WowUp client, and don't see this anymore.

**Comment by jliddev** [comment]
good deal.
