### ISSUE TITLE
Installed Addons list - Icons not loading

### ISSUE THREAD

**Issue by WybeBosch** [jliddev/WowUp#38]
Hey there! ran into this issue after loading all my addons into the application. 

![icons not loading](https://user-images.githubusercontent.com/40889930/92028902-0f284a80-ed65-11ea-9f17-2967f6c2a5e3.png)

Addons that dont have icons correctly get your place holder icon, but addons that are actually Supposed to have icons
seem to not be loading them no matter what i do (restart, refresh, re-scan etc. )

When i switch to the "Get Addons" tab, addons in the list there are properly getting icons(or rather their screenshots)

Are addons supposed to have their "category" icons? or the main screenshot that they use As icon?

**Comment by jliddev** [comment]
Well that's not ideal. If you go to the options tab and hit Show Log Files, could you send me the latest? Addons will have whatever the provider gives for the first image typically.

**Comment by WybeBosch** [comment]
[wowup-logs20200902_001.txt](https://github.com/jliddev/WowUp/files/5164558/wowup-logs20200902_001.txt)

Just to check... the zipfile containing the program exe IS the program right? 
its not supposed to be a installer for WoWUp ?

**Comment by jliddev** [comment]
There is currently no installer thats correct. Looks like theres an issue when its trying to create the thumbnails :/

**Comment by jliddev** [comment]
Could you check if there's a cache folder located at %LOCALAPPDATA%\WowUp ?

**Comment by WybeBosch** [comment]
Hmmm.. might have found why? in the log i send you obfuscated the name of my PC, but below you can see the actual pc name

the URL your application is trying to use to acces the thumbnails is 
`C:\Users\Wybe%20van%20den%20Bosch\AppData\Local\WowUp\Cache\Thumbnails\818-thumb.jpg`

while the actual URL is 
`C:\Users\Wybe van den Bosch\AppData\Local\WowUp\Cache\Thumbnails\818-thumb.jpg`


I can find the appdata folder, and the thumbnails Are there, its just using the wrong path to get to them?

**Comment by jliddev** [comment]
Good eye, i'll get that patched asap

**Comment by jliddev** [comment]
Feel free to reopen if the latest doesnt fix it!

**Comment by WybeBosch** [comment]
Issue is fixed for me! Thanks for the fast response :D
