### ISSUE TITLE
Linux version

### ISSUE THREAD

**Issue by J4nsen** [jliddev/WowUp#4]
Hi,
with this issue I want to report my interest in a Linux version. So far I'm running the Windows version via wine, which works fine beside some visual glichtes.

Thanks a lot for this tool!

**Comment by jliddev** [comment]
I'll look into!

**Comment by jliddev** [comment]
Note to self C# GTK support seems shaky right now, might have to think about different implementation.

**Comment by jliddev** [comment]
If you're still interested let me know, i will try to get a linux version of 2.0 alpha out for you to try

**Comment by J4nsen** [comment]
I'm still interested!

**Comment by mewt666** [comment]
I'm also interested, if there's an alpha or beta to test!

**Comment by justin-shepherd** [comment]
Count me in also!

**Comment by rycon** [comment]
I’m interested as well

**Comment by jliddev** [comment]
Not a linux guy, is this someting youd expect to see ? WowUp-2.0.0-alpha.11.AppImage

**Comment by J4nsen** [comment]
Yes, AppImages are one of many possible ways to distribute software packages

**Comment by jliddev** [comment]
well i published that with the latest alpha, feel free to give it a go https://github.com/jliddev/WowUp/releases/tag/v2.0.0-alpha.11

**Comment by J4nsen** [comment]
The program starts, but I'm getting a more or less blank window.

![image](https://user-images.githubusercontent.com/3029093/96378857-38732d80-118f-11eb-89c9-afd03d7cac26.png)

```
[jan@vfio-pc0 tmp]$ ./WowUp-2.0.0-alpha.11.AppImage        
22:10:21.762 › Main starting
RES /home/jan/.config/WowUp/logs/main.log
22:10:21.766 › USER_AGENT WowUp-Client/2.0.0-alpha.11 (5.8.14-arch1-1; x64; +https://wowup.io)
RES /home/jan/.config/WowUp/logs/main.log
22:10:22.488 › found window state: {
  width: 900,
  height: 600,
  x: 1265,
  y: 466,
  isMaximized: false,
  isFullScreen: false
}
RES /home/jan/.config/WowUp/logs/main.log
TRAY
22:10:22.950 › Checking for update
RES /home/jan/.config/WowUp/logs/main.log
22:10:23.496 › saving window state
RES /home/jan/.config/WowUp/logs/main.log
22:10:24.155 › Update for version 2.0.0-alpha.11 is not available (latest version: 2.0.0-alpha.11, downgrade is allowed).
RES /home/jan/.config/WowUp/logs/main.log
22:10:24.156 › checkForUpdatesAndNotify called, downloadPromise is null
RES /home/jan/.config/WowUp/logs/main.log
UPDATE {
  versionInfo: {
    version: '2.0.0-alpha.11',
    files: [ [Object] ],
    path: 'WowUp-2.0.0-alpha.11.AppImage',
    sha512: 'GoJb4RyUH/t2hxFW4D1nl8WL0KgoecQoxp7T7f+LFWMo99npEtob3fTQeDZo2Lp7Gs8kEEtDPi0AYDJTw44hrw==',
    releaseDate: '2020-10-18T19:20:07.585Z',
    releaseName: 'v2.0.0-alpha.11',
    releaseNotes: '<p>Add zoom support shortcuts and ctrl + scrollwheel (by Linaori).<br>\n' +
      "Add version label to the 'Get Addons' page (by Chops).<br>\n" +
      'Updates to the addon detail page (by Flippey).<br>\n' +
      'Russian local updates (by Medok).<br>\n' +
      'Add the system notification for auto updates.<br>\n' +
      'Fix some column spacing.<br>\n' +
      'Telemetry for user actions added.<br>\n' +
      "Fix a bug not allowing users to uninstall an addon with no 'installed folders'.<br>\n" +
      'Hopefully less issues with installing multiple addons at once.<br>\n' +
      'Fix some errors related to addons imported from GitHub.</p>'
  },
  updateInfo: {
    version: '2.0.0-alpha.11',
    files: [ [Object] ],
    path: 'WowUp-2.0.0-alpha.11.AppImage',
    sha512: 'GoJb4RyUH/t2hxFW4D1nl8WL0KgoecQoxp7T7f+LFWMo99npEtob3fTQeDZo2Lp7Gs8kEEtDPi0AYDJTw44hrw==',
    releaseDate: '2020-10-18T19:20:07.585Z',
    releaseName: 'v2.0.0-alpha.11',
    releaseNotes: '<p>Add zoom support shortcuts and ctrl + scrollwheel (by Linaori).<br>\n' +
      "Add version label to the 'Get Addons' page (by Chops).<br>\n" +
      'Updates to the addon detail page (by Flippey).<br>\n' +
      'Russian local updates (by Medok).<br>\n' +
      'Add the system notification for auto updates.<br>\n' +
      'Fix some column spacing.<br>\n' +
      'Telemetry for user actions added.<br>\n' +
      "Fix a bug not allowing users to uninstall an addon with no 'installed folders'.<br>\n" +
      'Hopefully less issues with installing multiple addons at once.<br>\n' +
      'Fix some errors related to addons imported from GitHub.</p>'
  }
}
```

**Comment by jliddev** [comment]
i'll give it a try on an ubuntu vm and see what i can find.

**Comment by tmzhuang** [comment]
> well i published that with the latest alpha, feel free to give it a go https://github.com/jliddev/WowUp/releases/tag/v2.0.0-alpha.11

How do you run the program? I didn't see a prebuilt binary, and didn't see instructions for building from source.

**Comment by jliddev** [comment]
I was able to get it to run but I need a Linux wow player to hop on discord with me probably so we can fix it

**Comment by tmzhuang** [comment]
> I was able to get it to run but I need a Linux wow player to hop on discord with me probably so we can fix it

I'd be glad to help, but I'm on Arch Linux, so might be better for someone on Ubuntu. If you don't mind a slightly different distro, I can message you my discord info.

**Comment by mewt666** [comment]
> > well i published that with the latest alpha, feel free to give it a go https://github.com/jliddev/WowUp/releases/tag/v2.0.0-alpha.11
> 
> How do you run the program? I didn't see a prebuilt binary, and didn't see instructions for building from source.

I just ran ./WowUp-2.0.0-alpha.11.AppImage and got the same as J4nsen; blank window with size controls under the view menu.

**Comment by codyf86** [comment]
Hey .14 works in terms of the UI but I can't set the installation paths even if I take the spaces out of the directory its located it (thought it was an escaping a space \ issue, but doesn't appear to be).
![Screenshot at 2020-10-21 08-26-25](https://user-images.githubusercontent.com/5041404/96734008-513e3780-1377-11eb-9dd4-039165e20bc3.png)

**Comment by jliddev** [comment]
try selecting just the world of warcraft folder, not the retail folder

**Comment by codyf86** [comment]
Hell yeah it works great now lol thanks :)

**Comment by codyf86** [comment]
![Screenshot at 2020-10-21 08-30-51](https://user-images.githubusercontent.com/5041404/96734401-beea6380-1377-11eb-91a1-f9e6a4956dab.png)

**Comment by jliddev** [comment]
hey thats awesome :D

**Comment by codyf86** [comment]
Retail and Retail ptr addons show up, but classic addons just show a blank screen after it tries to scan them although it finds the folder fine, maybe a small typo or something also on the main screen need to add a gui slider on the right it cuts off after classic addon channel and also you can't scroll up and down through the addons.

No big deal glad it works, since it puts the things that need updated at the top.  I'll hit your patreon up soon.

**Comment by jliddev** [comment]
Closing this as it seems to work :D
