### ISSUE TITLE
Request: Accept commandline parameters

### ISSUE THREAD

**Issue by dsdann** [jliddev/WowUp#44]
My ideal use case for this would be the ability would to be able to pass commands to this via command line silently

For example:

C:\wowup\wowup.exe -version:retail -update -silent

I could then set this a scheduled task on start up to call it, it runs, updates and then closes.

Cheers,
Dan

**Comment by jliddev** [comment]
Cool i'll think about the easiest way this might be done.

**Comment by Proxaaa** [comment]
Support addon URL as a startup argument to import and install it

**Comment by jliddev** [comment]
-m to launch minimized and -q to quit after auto updates has been added 1.18.0
