### ISSUE TITLE
WowUp not recognizing ElvUI Update

### ISSUE THREAD

**Issue by EkaterinaR** [jliddev/WowUp#46]
ElvUI current version (as of  time of writing 10/09/2020) is 11.52. WowUp is still showing the latest version as 11.51

![image](https://user-images.githubusercontent.com/38995757/92678166-ba8a5e00-f368-11ea-8ec2-a08723bdbd95.png)

![image](https://user-images.githubusercontent.com/38995757/92678193-c7a74d00-f368-11ea-938e-deba51ddf698.png)

With my addons, I'm currently unable to determine if any of the other TukUI addons are not updating, but I'm having not issue with updates via Curse.

**Comment by jliddev** [comment]
can you try doing a re-scan and see if it helps?

**Comment by EkaterinaR** [comment]
Re-scanning detects the latest version. 

Hmm.

**Comment by jliddev** [comment]
It should be fine going forward without a rescan, but if not feel free to file another issue 👍
