### ISSUE TITLE
beta support

### ISSUE THREAD

**Issue by rwygand** [jliddev/WowUp#5]
Blizz just announced support for addons for beta. It would be great if WoWUp could add support for a new folder, beta/ just like retail/ and classic/

**Comment by jliddev** [comment]
I would be happy to add this feature, if you know the name of the folder the beta client lives in its easy to add.  I assume its something similar to _retail_ or _classic_. I am not cool enough to have been invited to beta so far :P

**Comment by rwygand** [comment]
it's _beta_

**Comment by jliddev** [comment]
This should be working, but i cant personally test it since im not cool enough for an invite :P let me know if there's issues.
