### ISSUE TITLE
WTB: "Update Retail + Classic" button

### ISSUE THREAD

**Issue by teelolws** [jliddev/WowUp#51]
Maybe put it next to this dropdown: 
![image](https://user-images.githubusercontent.com/49792789/93290033-e9ef0e00-f833-11ea-8bbc-681c0595ab8b.png)

Offering 9001 copper.

Thats OVER NINE THOUSANNNNNNNNNNNNNNND!!!!!!!!!!!!!!!!!11111111

**Comment by jliddev** [comment]
All Teelo issues are marked Invalid

**Comment by jliddev** [comment]
Will probably kick this off till 2.0 and make it a config somewhere
