### ISSUE TITLE
Enhancement: Add "Microsoft.Windows.Common-Controls" to Manifest to enable Windows theming support for controls and dialogs

### ISSUE THREAD

**Issue by lloydbates** [jliddev/WowUp#53]
WowUp v1.16.1

Windows message dialogs displayed by WowUp do not use the modern common controls present since Windows XP.
This is a very minor complain as it is purely optics and only for the very few Windows dialogs, like the confirmation which is displayed when and addon is uninstalled.

See screenshot:
![grafik](https://user-images.githubusercontent.com/4516420/93698595-3b3e1c80-fb16-11ea-9f32-314651ebd5ca.png)

The change required is very small, you have to edit your predefined manifest.xml, it looks like you are using a default one which is already anotated with some optional changes, to include the common controls.

```xml
  <dependency>
    <dependentAssembly>
      <assemblyIdentity type="win32" name="Microsoft.Windows.Common-Controls" version="6.0.0.0" processorArchitecture="*" publicKeyToken="6595b64144ccf1df" language="*" />
    </dependentAssembly>
  </dependency>
```

**Comment by jliddev** [comment]
I added this to 1.17.0-beta.1 if you want to give it a try, the dialogs look the same on my system though.

**Comment by lloydbates** [comment]
![grafik](https://user-images.githubusercontent.com/4516420/93715114-90564e80-fb67-11ea-9b60-4a52979f110d.png)
Looks fine for me, thank you very much.
