### ISSUE TITLE
Updater to 1.61 from 1.60 not working

### ISSUE THREAD

**Issue by missebet** [jliddev/WowUp#55]
Website says it's downloading version 1.61 but installs 1.60, when I attempt to update to 1.61 it fails
Please see attached log file, as i have no idea where/what is causing the issue.
Thanks 
[wowup-updater.log](https://github.com/jliddev/WowUp/files/5257646/wowup-updater.log)

**Comment by jliddev** [comment]
Looks like you are missing the task kill app, will dig into fixing it asap

**Comment by jliddev** [comment]
I pushed a new version of the updater, WowUp should pick it up if you restart it then try updating again.

**Comment by missebet** [comment]
Still wasn't able to get it to update, but installing 1.62 went smoothly and the update messages are gone. Thank you for your help and time to develop this. Very happy to have found a new addon updater, that is NOT the overwolf.

**Comment by jliddev** [comment]
Sorry it didnt work, my change also caused some issues with virus detection on the updater so i had to roll back , but glad you got updated :D
