### ISSUE TITLE
Releases Since 1.16.1 Showing Old Addon Versions

### ISSUE THREAD

**Issue by Cilraaz** [jliddev/WowUp#56]
Both version 1.16.2 and 1.16.3 show me older version of addons. I've tried with the addon types set to both alpha and stable, but get the same results. Here is a part of my addon list in 1.16.1:
![WowUp-1 16 1](https://user-images.githubusercontent.com/12204132/94062310-81b0a700-fdb4-11ea-952c-6287bdbe0380.png)
Here's the same list from 1.16.3:
![WowUp-1 16 3](https://user-images.githubusercontent.com/12204132/94062383-9856fe00-fdb4-11ea-865f-1ecd5aa2a9aa.png)

I've tried the 1.17.0 betas as well and it acts the same.

**Comment by jliddev** [comment]
There was a bug fix in 1.16.3 that fixed the issue of the actual latest alpha/beta not being selected. 1.16.3 is showing you the correct latest alpha builds for those addons.

Essentially 1.16.1 was showing the latest alpha/beta incorrectly probably most of the time.

**Comment by jliddev** [comment]
Considering that this feels too strict, might rework it to be select latest

**Comment by Cilraaz** [comment]
If alpha is the selected addon type, should it not show a beta or release version if it's newer, rather than just the latest alpha? I was under the assumption that it worked like the Twitch client, in so far as the build type selector essentially being a level of acceptable risk, where stable is "only show release versions", beta is "show the latest of release or beta versions", and alpha is "show me the latest of any version".

In any case, not trying to demean in any way. I love your client and the fact that it's taken the place of multiple other clients (especially the way too bloated Twitch app). Thanks for the work you've put into it!

**Comment by jliddev** [comment]
Nah you're right im working on making it do that very thing right now :D

**Comment by jliddev** [comment]
Give 1.16.4 a try

**Comment by Cilraaz** [comment]
Sorry, I was afk for a while. I tried 1.16.6. It looks like it's working right when addon type is set to alpha. I can't verify if it's working properly for beta or stable, though, as I'm already on the latest alphas of all of my addons.

**Comment by jliddev** [comment]
Sounds good thanks :)
