### ISSUE TITLE
Startup to System Tray

### ISSUE THREAD

**Issue by Shadow00Caster** [jliddev/WowUp#57]
As an enhancement/feature request to the Windows version, add option to startup minimized to tray instead of minimized to taskbar.

**Comment by SiJiL82** [comment]
Seconded, would love to be able to have this auto start with Windows and just hide itself and auto update and never have to do anything with it!

**Comment by Evolutious** [comment]
Thirded! (is that a word) Set it and forget it would be awesome :D

**Comment by Nostix** [comment]
Fourthed! Would love to see something like that!

**Comment by Noxis-source** [comment]
@Shadow00Caster @SiJiL82  @Evolutious  @Nostix 
With the latest beta you can add an ink to your startup folder and add -m to it to implement this behavior
Check out FAQ at discord

**Comment by Evolutious** [comment]
> @Shadow00Caster @SiJiL82 @Evolutious @Nostix
> With the latest beta you can add an ink to your startup folder and add -m to it to implement this behavior
> Check out FAQ at discord

Thank you! Tested and looks good! :D  Also, you may want to update the FAQ in Discord to state that this minimizes to the System Tray, not the Taskbar (could be misleading for some and they wonder if the application has even started).

**Comment by jliddev** [comment]
Feature released in 1.18.0
