### ISSUE TITLE
[Request] Multiple add-on selection

### ISSUE THREAD

**Issue by Braxusz** [jliddev/WowUp#58]
Would be be possible to allow the selection of multiple add-ons at a time, or all at once (via ctrl+click or shift+click) and perform actions such as delete, re-install, toggle auto update etc.?

**Comment by jliddev** [comment]
This is partially done in 1.18 beta for Auto Update

**Comment by Braxusz** [comment]
I saw that in the change log, definitely going to be helpful. Thank you.

**Comment by jliddev** [comment]
Released in 1.18.0
