### ISSUE TITLE
developer getting started in readme?

### ISSUE THREAD

**Issue by rwygand** [jliddev/WowUp#6]
I'm interested in helping out, but I've not used Visual Studio in 2 decades. A getting started guide for would-be developers in the README.md would be super useful to me, and potentially others.

**Comment by jliddev** [comment]
Sure, I added a wiki page, hopefully that covers everything. If you find something needs to be added let me know!

[Wiki](https://github.com/jliddev/WowUp/wiki/Development)

**Comment by rwygand** [comment]
Thanks, I'll take a look!
