### ISSUE TITLE
[Pull request] I Need to be able a pull request

### ISSUE THREAD

**Issue by ayell** [jliddev/WowUp#60]
Hi,

Firstly , gg for this app ! 

I would like to help u in the developement on this app . i do the feature "run on starup" but i cant submit my code .

Can u add my account to able to make some pull request ? :)

PS : I created my branch

**Comment by ayell** [comment]
Here the final result 

![capture20201002171336888](https://user-images.githubusercontent.com/15988065/94939637-b4545100-04d2-11eb-9183-5309258ce4fa.png)

**Comment by jliddev** [comment]
You should be able to crate a PR from your fork for review here.
