### ISSUE TITLE
BTWLoadouts set to stable but shows alpha update

### ISSUE THREAD

**Issue by yajinni** [jliddev/WowUp#62]
![image](https://user-images.githubusercontent.com/9600587/94462546-af696780-0189-11eb-9791-08690c6d1f25.png)

**Comment by jliddev** [comment]
That is the correct version. This author has no stable releases, so in order to show you something WowUp picks the latest.
![image](https://user-images.githubusercontent.com/20467484/94463583-c8bae580-0182-11eb-8ecd-32e53c47f5a4.png)

**Comment by Rustyb0y** [comment]
Other addon tools are not showing this as an update.  The type is clearly set to Alpha so it probably never should show as a stable release.

**Comment by jliddev** [comment]
discussing the same thing in #63 closing this
