### ISSUE TITLE
Protect newer (alpha/beta) AddOns from being overwritten

### ISSUE THREAD

**Issue by michaelvolz** [jliddev/WowUp#63]
first: Very nice tool. love it.

It would be great to check the installed version number with the new one and cancel any update if it is higher. 
Just destroyed my PTR folder with old versions.

**Comment by jliddev** [comment]
Im not sure I understand. Newer versions of the addon for your PTR client were overwritten by older ones?

**Comment by michaelvolz** [comment]
Example: I had manually installed WeakAuras 3.x beta on the PTR, WowUp installed the latest 2.x beta version over.

PTR was configured to install the latest beta version.

It might be better just to ignore a newer version.

**Comment by jliddev** [comment]
Currently, if beta is the selected channel, the app will select the latest addon and include betas which is probably desired for most users. However, it might be worth adding  a toggle to set it to 'strict' channel mode for certain clients if you only want to install beta/alpha specifically

**Comment by michaelvolz** [comment]
This is not my point. You can have 2.x betas and 3.x betas at the same tim.

Just compare the version in the .TOC file and don't overwrite newer versions, that's it.

If I have 3.x beta/alpha/whatever installed, please don't overwrite it with a 2.x beta/alpha/whatever!

**Comment by jliddev** [comment]
Newer is relative. There is no standard versioning system so parsing the version in the toc would be largely pointless. In this instance why not just set the addon you know isn't on curse to ignore and leave it be?
