### ISSUE TITLE
app uses WoW base directory for all games instead of specific file paths

### ISSUE THREAD

**Issue by Ra-er** [jliddev/WowUp#65]
It's probably not an "issue" per se, but I'd feel more comfortable specifying which Addon directory for each game type (Retail, Beta or Classic) than leaving it up to the app to append _retail_, _beta_, _classic_. 

It feels awkward that for all the game types it scans the entire WoW dir.

**Comment by jliddev** [comment]
It does not search for a WoW dir. The app pulls the paths to your WoW directories from your blizzard app database. You are free to change them in the options page as you like.

**Comment by Ra-er** [comment]
![image](https://user-images.githubusercontent.com/17073835/94514264-c5f5da00-01ee-11eb-8703-ec5dbd605534.png)

**Comment by jliddev** [comment]
In this case you need to select that World of Warcraft folder, not the addons folder.
