### ISSUE TITLE
Its 2020, we must push Github (or any git) source

### ISSUE THREAD

**Issue by wkrueger** [jliddev/WowUp#66]
Its impressive how we still update addons by uploading ZIP files to websites.

We could have some sort of standard. Coding comunities have package repositories and CLI tools. Have standards like `package.json`s or `POM.xml`s.

What we need is some sort of standard package repository, maybe even dependency managers. Something easy for the beginner and powerful for the experienced.

Developing yet another GUI without recognizing the community real needs (=infrastructure) will end up in another isolated and futurely dead effort. Wowup is great, but can be seasonal.

**Comment by jliddev** [comment]
This is true, I am working on an infrastructure for something like this but i am only one person. It will come eventually if people still want it :)

**Comment by wkrueger** [comment]
people wonder "if theres not curseforge where will I upload releases now"

github is great because addons developers can just push releases to github releases (like weakauras does) and any updater tool can read from that without relying on Curse or whatever

**Comment by jliddev** [comment]
see #36
