### ISSUE TITLE
Add more options to NotifyIcon

### ISSUE THREAD

**Issue by Noxis-source** [jliddev/WowUp#67]
Change the icon if updates are available

Support double clicks to open the main window

Add context menu entries for common actions and switches
* Show main window
* Show options
* Change client type
* Check for updates
* Update all
* Re-scan
* Check/install client updates

**Comment by Noxis-source** [comment]
https://github.com/jliddev/WowUp/issues/85

**Comment by Noxis-source** [comment]
Well, looks like the Client Type switch should wait for a better time

**Comment by jliddev** [comment]
i know you did this, we lost it somewhere? made a new ticket specifically for 2.0 #206
