### ISSUE TITLE
Add version columns to Get Addons tab

### ISSUE THREAD

**Issue by panoplybez** [jliddev/WowUp#69]
Is it possible to add the version columns that you have on My Addons to the Get Addons tab to make it easier to see how old/new a given addon is before installing it?

**Comment by pax0707** [comment]
Basically, all the columns Curse app used to have.

**Comment by Noxis-source** [comment]
@panoplybez Maybe it would be better to show a column with the last update date? I am asking because client version should always be equal to the selected client type and the version column will always show the latest version

@pax0707 Would you please specify exactly which columns you wish to see? I assume categories, but it is kind of pointless until https://github.com/jliddev/WowUp/issues/73 is implemented

**Comment by Noxis-source** [comment]
Also, https://github.com/jliddev/WowUp/issues/12

**Comment by panoplybez** [comment]
I'm thinking about that. How about both? The problem is, some addons still work, even if their listed version is like.. 8.0.1 or something. I have at least 6-7 addons in my list that are showing me versions older than 8.3.0 for example. But what I'm thinking is that showing the version when you're browsing also gives you a good idea of how old something might be. I leave it up to you of course, but that's where my thinking was. I can rule out anything older than 8.0 but could still try to use something marked 8.0.1 if its last update was within the past 2 years.

**Comment by pax0707** [comment]
Installed: Channel, Downloads number, Install date, Last update date, Current version, Available version.

So you can see what's been updated, not updated for a long time, along those lines.

**Comment by Noxis-source** [comment]
Thank you for the clarification. Well, I suppose some additional information never killed nobody :) Though, it is necessary to consider that screen space may be limited. Maybe a column chooser can make some use.

**Comment by pax0707** [comment]
Exactly.

Give people that want to an option to enable more columns, leave it at default for "normal" users.

**Comment by Noxis-source** [comment]
Well, here is how I see it

My addons:
![6CRVUChtfx](https://user-images.githubusercontent.com/15377938/95024503-10aea080-068c-11eb-93a9-1e2c52b913db.png)

Get addons:
![QwkwoH2e3m](https://user-images.githubusercontent.com/15377938/95024506-14dabe00-068c-11eb-8b70-d9ff13c8d66e.png)

Does it look good?

**Comment by panoplybez** [comment]
Whoa that looks like even more than I suggested, but maybe that comes from Pax's suggestions heh.
Will those be optional show/hide columns? 

For Get Addons, can you add Game Version column as well? I feel like some of those make more sense if they are swapped. Like move Categories from My Addons over to Get Addons as it makes more sense when browsing, to me. But I like it!

**Comment by pax0707** [comment]
Great work!
Love it.

**Comment by Noxis-source** [comment]
> Will those be optional show/hide columns?

Working on that

> For Get Addons, can you add Game Version column as well?

Sure

> move Categories from My Addons over to Get Addons

Both My and Get display Categories :)

**Comment by Noxis-source** [comment]
Considering that the app migrates to electron, this will get delayed for some time

**Comment by jliddev** [comment]
This is issue is kind of a bunch of feature requests all in one. Most of this has been added in 2.0 via the new Released At colum and the details panel. Categories are non trivial and have their own issue #73
