### ISSUE TITLE
Windows Installer

### ISSUE THREAD

**Issue by rwygand** [jliddev/WowUp#7]
Hi!

It'd be great if there were a windows installer instead of downloading an .exe file. I was looking at possibly adding one, but I'm not sure I have a version of VS that lets me created app installers.

**Comment by jliddev** [comment]
It's probably unlikely for this iteration of the app. It's much more likely in the cross platform version that im working on as well :)

**Comment by jliddev** [comment]
This is actually complete in 2.0 right now :)
