### ISSUE TITLE
Option to remove all files related to an addon ?

### ISSUE THREAD

**Issue by Arcky14** [jliddev/WowUp#74]
Hi, would it be possible to add an option to remove all files related to an addon when it is removed, such as addon_name.lua and addon_name.lua.bak ? For example when I remove "Pawn", it would also remove WTF/Account/account_name/SavedVariables/Pawn.lua and WTF/Account/account_name/server_name/character_name/SavedVariables/Pawn.lua
Twitch App was able to do it once but it doesn't work anymore.

Thanks !

**Comment by jliddev** [comment]
Currently doing anything with the WTF folder is low on the backlog and will require quite a bit of planning to not scare people.
