### ISSUE TITLE
McAfee reports virus detection on WoWUpUpdater.exe

### ISSUE THREAD

**Issue by db-toolstech** [jliddev/WowUp#77]
After downloading and installing the latest update to the app, McAfee reports a threat detection.  While this may be a false positive, I am reporting it here for review:

Threat name: Real Protect-EC!CFB4F7CC7FCC
Process: C:\Users\<username>\AppData\Local\WoWUp\WowUpUpdater.exe

**Comment by jliddev** [comment]
What version of WowUpdater did you run this on?

**Comment by jliddev** [comment]
VirusTotal says the Latest (1.0.4) is fine 
https://www.virustotal.com/gui/file/c2c5e59c5877ad9fd6de18af7639761478aabd9119c2711e847ff4a41adf7921/detection

**Comment by db-toolstech** [comment]
This detection was immediately following the download of the 1.17.1 version of WowUp via the in-app download prompt.

**Comment by jliddev** [comment]
The updater app lives in %LOCALAPPDATA%\wowup

**Comment by db-toolstech** [comment]
I restored the file from the McAfee quarantine and it the file details do say the file version of the updater is 1.0.4.0

**Comment by jliddev** [comment]
Strange googling that error code doesn't tell me much

**Comment by db-toolstech** [comment]
After restoring the file from the McAfee quarantine, a manual scan of the file reports no errors and I haven't had it alert again so far.  I did double check that the file didn't get automatically placed in my whitelist by restoring it, so I don't really know why the manual scan passes when earlier activity reported it as a threat.

**Comment by jliddev** [comment]
Gonna close this for now, if it comes up again let me know.
