### ISSUE TITLE
Auto Update Feature

### ISSUE THREAD

**Issue by CleverChrononaut** [jliddev/WowUp#78]
Does the Auto-Update feature under the Options for each World of Warcraft Installation, only work on newly installed addons?

I have over 100 addons and checking the right-click option for each addon had Auto-Update off.

If this is intended then disregard, just doesn't seem like a very useful global feature if turning it on in the options only affect new addons.

**Comment by jliddev** [comment]
Please try the latest 1.18 beta, i added a the ability to bulk select and edit the auto update setting.

**Comment by CleverChrononaut** [comment]
Awesome! Thanks.
