### ISSUE TITLE
Addon update status

### ISSUE THREAD

**Issue by Rustyb0y** [jliddev/WowUp#79]
I presume WowUp keeps it's own record if an addon has a new version available.  However when "Check Updates" is selected it seems to ignore checking the addons that have already been flagged for an update.  If you update the addon outside of WowUp it will constantly flag it as needing an update.

Twitch updater
![image](https://user-images.githubusercontent.com/54157890/94759384-15046080-03e3-11eb-84e1-62dfe0525f3e.png)

WowUp after pressing Check Updates/Restarting
![image](https://user-images.githubusercontent.com/54157890/94759403-23eb1300-03e3-11eb-92ff-f5d20f614257.png)

**Comment by jliddev** [comment]
If you update an addon outside of WowUp, you can click on the 'Re-Scan Folders' button to pick up changes.

**Comment by Rustyb0y** [comment]
Thanks for you response.  Yes I am aware that you can do this.  Just wanted to express the opinion that the addon should keep track of these changes through the refresh button.  It does seem weird that it would check every other addon and not bother with ones already flagged to be updated.

**Comment by jliddev** [comment]
The refresh button does not check the file system and hopefully been renamed to be clearer. doing a scan of every folder is heavy/slow.
