### ISSUE TITLE
WoWUp trying to install release version even when alpha preference set

### ISSUE THREAD

**Issue by Kilmatar** [jliddev/WowUp#80]
Setup "Alpha" preference for addons for retail WoW.
WoWUp suggest to update already installed addons with release version.
For example: Ace3 "r1239-alpha" installed.
WoWUp suggest to install "Release-r1227" version despite the "Alpha" preference is set

**Comment by CherylAoife** [comment]
Same issue. I just installed WoWUp and noticed this issue. I have Alpha preference set on all my installations, and it works as it should on all but Retail.

**Comment by Takika** [comment]
It works with Classic, but not with Retail.

**Comment by CherylAoife** [comment]
Now it's doing it with the Beta too.

**Comment by jliddev** [comment]
I guess im lost, are you not seeing this version when selecting the alpha channel of Ace3? the client type doesnt affect how the app chooses what version to show you.

![image](https://user-images.githubusercontent.com/20467484/95291370-fc59d780-0834-11eb-8f67-10a77ae45568.png)

**Comment by professionaltart** [comment]
![image](https://user-images.githubusercontent.com/28383689/95292570-70d85900-08bd-11eb-8c16-acf90400ea08.png)
![image](https://user-images.githubusercontent.com/28383689/95292660-a4b37e80-08bd-11eb-8b52-c71d41cbd463.png)


If I go and manually select that addon to use the alpha release channel:
![image](https://user-images.githubusercontent.com/28383689/95292745-ce6ca580-08bd-11eb-8980-71bcc07a50fa.png)

Even if I Re-Scan Folders, by default it is setting every addon to the release channel.

**Comment by Kilmatar** [comment]
1.19.0-beta.2 corrected the problem!
After folders rescanning correct versions is suggested to download.

Looks like this ticket can be closed. At least for me now everything is looking good

**Comment by Veyska** [comment]
Just downloaded WoWUp to give it a go and despite flipping over to the beta build of the app all the addons are still showing they're set to Stable rather than Alpha as per the Default Addon Channel.  Possibly that setting isn't being respected or passed down to the various addon entries?  Manually setting an addon to Alpha sticks, but that would be... tedious to do wholesale.

(Have tried switching to beta version of WoWUp, as stated above, have also tried Re-Scan Folders several times as well as flipping the Default Addon Channel setting around through all possible options and even changing which game install I was looking at on the off chance that triggered the right sort of reloading (I've seen weirder things happen in coding).)

**Comment by professionaltart** [comment]
Updated to the 1.19.0-beta.2 client:
- addons are all still set to alpha channel by default in Options
- re-scanned folders for addons
- checked updates for all addons
- addons are still set to stable channel by default

If I shift-select to change a group of them to manually use the alpha channel, and then check for updates, it seems to persist.

**Comment by CherylAoife** [comment]
After I'd updated to the 1.19.0-beta.2 client, I rescanned the folders and addons in Retail were still set to Release; addons in Beta were still set to Beta.

I then manually changed each addon to Alpha in both Retail and Beta. 

> Updated to the 1.19.0-beta.2 client:
> 
> * addons are all still set to alpha channel by default in Options
> * re-scanned folders for addons
> * checked updates for all addons
> * addons are still set to stable channel by default
> 
> If I shift-select to change a group of them to manually use the alpha channel, and then check for updates, it seems to persist.

**Comment by jliddev** [comment]
Enhancements have been made to how these channels are handled in 2.0.
