### ISSUE TITLE
Unable to designate correct WOW folder

### ISSUE THREAD

**Issue by Kaalkingdom** [jliddev/WowUp#81]
I am unable to designate the correct WoW folder for the different versions of the game.   The name of my two folders are:

_retail_  (you are not seeing the underscores _ retail _ so I put it here with spaces added)
_classic_  (you are not seeing the underscores _ classic _ so I put it here with spaces added)

Is there a fix for that?

**Comment by jliddev** [comment]
you need to select the folder one above retail or classic, typically "World of Warcraft"

**Comment by Kaalkingdom** [comment]
Got it!   Thank you!

**Comment by jliddev** [comment]
perfect 👍
