### ISSUE TITLE
'Recently Updated'

### ISSUE THREAD

**Issue by Evolutious** [jliddev/WowUp#82]
Feature Request

It would be nice to have addons reflect those that have been 'Recently Updated' within the Status column in the UI so when you have auto update turned on and updates are automatically performed, you can go into the app and see what was updated. As it stands, there is no way to tell what was updated. Remove the 'Recently Updated' indicator after say 24 hours or something.

**Comment by Daeveren** [comment]
Yeah knowing what you've updated recently, even right that moment after you update addons is really useful.

**Comment by linaori** [comment]
@Evolutious, @Daeveren, I've just created this PR for the 2.0 version #221, would this be sufficient?

**Comment by Evolutious** [comment]
> @Evolutious, @Daeveren, I've just created this PR for the 2.0 version #221, would this be sufficient?

This looks fantastic! Yes, that would address my ask. thanks!

**Comment by jliddev** [comment]
Deployed with 'Installed At' column.
