### ISSUE TITLE
Cant find the Aardvark and Swarm addons

### ISSUE THREAD

**Issue by Walkerbo** [jliddev/WowUp#84]
Hi 

I have the Aardvark and Swarm addons installed yet they do not show in the "My Addons" list.

Both of these addons do show as installed on the Twitch app.

I note that both of these addons work on both the current and classic versions.

**Comment by jliddev** [comment]
I was able to install both Aardvark and Swarm via Twitch and then detect them in WowUp 1.17. If you like you can to to the "Options" tab and click on the "Dump Debug Data" button, then grab the latest log file and send it my way, we can dig deeper.

**Comment by Walkerbo** [comment]
Please find attached the log file.
[wowup-logs20201002.txt](https://github.com/jliddev/WowUp/files/5316117/wowup-logs20201002.txt)

**Comment by jliddev** [comment]
Have you modified the Aardvark or Swarm folder in any way? the fingerprint for those dont return anything from curseforge.

**Comment by Walkerbo** [comment]
Sorry for the delayed response.

Yes, I had modified both addons, (I am the author for both), but I solved this by installing them both though the "Get Addons" tab.
They did not overwrite the addons but they did then show in the installed addons list; then I just chose to ignore them both.

Thanks for this app, I can now get rid of the Twitch app altogether.

**Comment by jliddev** [comment]
Great :D
