### ISSUE TITLE
Doesn't cleanup old version when updating.

### ISSUE THREAD

**Issue by tomrus88** [jliddev/WowUp#87]
Each time you run new version of wow up, new folder being created at
`c:\Users\<user_name>\AppData\Local\Temp\.net\WowUp\`
Each folder is ~100MB. This will quickly end up many gigabytes of wasted space.

You can probably switch to .NET 5.0 RC2 which only extracts native dependencies to disk while loading managed assemblies directly from single file bundle.

**Comment by jliddev** [comment]
Will probably have to revist this at a later date as WPF does not currently support .net 5.

https://github.com/dotnet/wpf/blob/master/roadmap.md

**Comment by tomrus88** [comment]
> Will probably have to revist this at a later date as WPF does not currently support .net 5.

That's not true. WPF is supported by .NET 5.0, but you have to use latest daily bits (currently [RC2]([url](https://aka.ms/dotnet/net5/rc2/Sdk/dotnet-sdk-win-x64.exe))), because RC1 has some issues with single file publish. Final version of .NET 5.0 will be released next month on November, 10.

There's also some changes required to make it work with .NET 5.0: https://github.com/tomrus88/WowUp/commit/542ebeacf6180a0f06b8bbebade424dee0bd8f55

**Comment by jliddev** [comment]
Seems worthwhile, submit a PR when it gets to general release since it looks like you already did the leg work :D

**Comment by jliddev** [comment]
Since 2.0 isnt in .net we probably dont need this.
