### ISSUE TITLE
How can I easily set all addons to automatically update?

### ISSUE THREAD

**Issue by nzall** [jliddev/WowUp#88]
I want to use the latest release version of my addons at all times and don't want to have to manually check for and install updates every day. I know I can set a specific addon to auto update by right-clicking them, but is there a way to set ALL addons to auto update without having to do this for every addon manually?

**Comment by Noxis-source** [comment]
@nzall Multiselect feature is available in beta
![WowUp_S7CLVPifyf](https://user-images.githubusercontent.com/15377938/94997872-aed03700-05b6-11eb-9a1c-7751e454b1bd.png)

**Comment by pax0707** [comment]
Would also love it if the option to set the addon channel would be added to multi-select dropdown.

**Comment by Noxis-source** [comment]
I believe the author is working on that
![Discord_dVhvCwjsCF](https://user-images.githubusercontent.com/15377938/95001593-0df07480-05d4-11eb-979f-1049601d809a.png)

**Comment by jliddev** [comment]
Closing this to lump it in with #58 which is currently in beta.
