### ISSUE TITLE
scanning

### ISSUE THREAD

**Issue by mspykerez** [jliddev/WowUp#9]
- all addons shows outdated when you first time start the app or when you perform a re-scan.
- WowUp takes a lot of time to scan/re-scan My Addons, other clients do this job way more quickly.

**Comment by jliddev** [comment]
The first time you run the app, it tries to guess what you have installed which is normal and takes a little bit. 
Doing a re-scan basically tells the app to forget everything it knows and re-guess, shouldnt really ever have to do it unless something funky changes in the database. To just check for latest updates hit refresh.
