### ISSUE TITLE
WowUp not finding a good few addons

### ISSUE THREAD

**Issue by linxus1981** [jliddev/WowUp#90]
I have a decent collection of adodns that were mostly installed via the curse client or twitch, but that dont seem to appear i wowUps list.  Ive attached the debug file from my last scan for addons
[wowup-logs20201004.txt](https://github.com/jliddev/WowUp/files/5322108/wowup-logs20201004.txt)

**Comment by jliddev** [comment]
Is this still happening in 1.18?

**Comment by linxus1981** [comment]
Yeah.  Did a quick check, seems to be happening to addons where the primary provider is Curse.  Addons like Gatherer/Greenwall/Blood shield tracker, are among those that dont show up but I have installed, and when I search for them in wowups get Addons page, they show up as coming from curse.

**Comment by jliddev** [comment]
Interesting, from your previous log it looks like there is an error happening while its trying to scan your curse folder. could you hop on discord would be faster if you'd like to debug :)

**Comment by jliddev** [comment]
@zakrn on discord if you do, forgot to mention

**Comment by jliddev** [comment]
Resolved in 1.18.1 :D
